title: Settings
data:
  site_name: 'Matthew Turland'
  social:
    -
      name: Github
      url: 'https://github.com/elazar'
      icon: site/social-icons/github.svg
    -
      name: Mastodon
      url: 'https://phpc.social/@elazar'
      icon: site/social-icons/mastodon.svg
    -
      name: Ko-Fi
      url: 'https://ko-fi.com/elazar'
      icon: site/social-icons/kofi.svg
    -
      name: Feed
      url: /feed.xml
      icon: site/social-icons/rss.svg
    -
      name: Email
      url: 'mailto:me@matthewturland.com'
      icon: site/social-icons/email.svg
